# Chapter 1. Deep learning basics

In [20]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


## Perceptrons

A perceptron is a mapping from $f:(x_1, ..., x_n) \rightarrow \{0,1\}$, whereby a __perceptron weights, sums (with bias) and thresholds__ the input.

We test the fact that a small change in parameters might cause a big change in the network output. We build perceptrons first, then build a vanilla network.

In [67]:
##Building a perceptron
class Perceptron:  
    randomShit = 5
    def __init__(self, num_of_inputs):
        self.num_inputs = num_of_inputs
        self.bias = np.random.uniform(0,1)
        self.weights = np.random.normal(0,1,self.num_inputs)
    def setWeights(self, *args):
        self.weights = np.array(args)
    def setBias(self, bias):
        self.bias = bias    
    def output(self, *args):
        variables = np.array(args)
        raw_output = np.sum(np.multiply(variables, self.weights)) + self.bias
        return int(raw_output >= 0)
    
class Layer:
    def __init__(self, num_of_perceptrons, num_of_inputs):
        self.num_of_perceptrons = num_of_perceptrons
        self.num_of_inputs = num_of_inputs
        self.perceptrons = np.array([Perceptron(self.num_of_inputs) for i in range(self.num_of_perceptrons)])
    def output(self, *args):
        return np.array([self.perceptrons[i].output(args) for i in range(self.num_of_perceptrons)])
    

In [65]:
## Trying out one output
np.random.seed(123)
p1 = Perceptron(3)
p1.weights
p1.bias
p1.output(0,1,2)

array([-0.95209721, -0.74544106,  1.73837013])

0.6964691855978616

1

In [66]:
## Trying out one layer
np.random.seed(123)
l1 = Layer(5, 3)
l1.output(0,1,2)

array([1, 0, 1, 0, 1])

In [69]:
Perceptron.randomShit

5

In [24]:
def output(*args):
    return np.array(args)

output(1,2,3)

array([1, 2, 3])

In [13]:
np.zeros(3)

array([0., 0., 0.])